### ISSUE TITLE
Undesirable Chrome tab behavior

### ISSUE THREAD

**Issue by incorrigible7** [FancyWM/fancywm#101]
**Describe the bug**
When dragging a chrome tab from one window to another, it is being treated as a window (which is desirable in every other case and the expected behavior) and therefore makes it difficult to drop it into another chrome window when the new target chrome window is already in a frame--eg, vertical frame--causing the window to dodge the tab back and forth, potentially until FancyWM hits some critical error and crashes (only had this happen once). 

**To Reproduce**
1. Attempt to drag a chrome tab from one window to another window that is in a frame. 
2. Have bad aim/continuously miss the target window. 

**Expected behavior**
After trying to replicate the behavior, I believe my issue is that if you do not aim exactly on the tab bar, FancyWM takes over and exhibits its normal behavior. Perhaps add a buffer of some sort, a time delay or a 'cushion' area around the tab bar area? Or better yet a customizable option if possible. 

**Desktop (please complete the following information):**
 - OS: w10
 - Version 21h2 64-bit

**Comment by veselink1** [comment]
Thanks for reporting. This might be tricky to fix. The workaround is to right-click on the tab and select "move tab to".

**Comment by mhowell86** [comment]
The way I've been able to successfully move tabs is to just not move the tab once you drag it to where the tab should be. The chrome window will eventually "settle down" and then the tab will be placed inside the chrome's tab area.

**Comment by incorrigible7** [comment]
> Thanks for reporting. This might be tricky to fix. The workaround is to right-click on the tab and select "move tab to".

I've been getting more into the habit of using that function as of late lol



> The way I've been able to successfully move tabs is to just not move the tab once you drag it to where the tab should be. The chrome window will eventually "settle down" and then the tab will be placed inside the chrome's tab area.

Holy shit, it works. Thanks for the tip! Though I find if you have another chrome window maximized (not being managed by FancyWM, I'm assuming) behind it (my partial workaround for stacking a window with other panels managed by FancyWM), it may still misbehave and not merge, taking it's own space, or merge with the maximized window.

**Comment by mhowell86** [comment]
This might require implementing an entirely new behavior for applications that use tabs like this. 

For example, having the window move just slightly to the side so it doesn't disturb chrome's tab native insertion behavior, then the user could move the tab more radically to a drop for normal FancyWM insertion behavior.
