### ISSUE TITLE
Ability to change window order in panel bar (via mouse)

### ISSUE THREAD

**Issue by incorrigible7** [FancyWM/fancywm#107]
**Describe the solution you'd like**
I would like to be able to drag and re-order the windows inside a panel via the panel bar at the top of the panel. 

**Describe alternatives you've considered**
FancyZones. Jk. 

**Additional context**
Haven't actually tried FancyZones, so I know nothing about them. FancyWM for lyfe! Plz no ban...

**Comment by veselink1** [comment]
Thanks for the feature request. Keyboard shortcuts can be used to achieve that in the latest version. Shift + Arrow swaps the focused window with the one in the respective direction. Use Shift+Left of Shift+Right in stack panels to change window order.

**Comment by incorrigible7** [comment]
Yes, I've rebound my movement hotkeys to a variation of WASD with and without shift, for swapping and moving windows respectively, to allow easier one-hand operation. Left the focus hotkeys alone as I don't use them. I think I made a comment on the default hotkeys being, eh, not the most convenient to use somewhere. Thanks for the consideration!
