### ISSUE TITLE
A standalone (non MS Store) version for purchase

### ISSUE THREAD

**Issue by cdiwoxv** [FancyWM/fancywm#110]
**Is your feature request related to a problem? Please describe.**
I work in a corporate environment where Microsoft Store is not supported. I use FancyWM a lot in my personal computer and really like it and believe it'll boost the productivity of me and the team I'm running.

My company is willing to pay for tools like FancyWM but just doesn't support downloading or purchasing from Microsoft Store.

**Describe the solution you'd like**
Provide a standalone version outside Microsoft Store that I can purchase, download, and install. Then I will purchase it for myself and my team. Other developers in my company may be interested in it as well.

**Describe alternatives you've considered**
I cannot think of an alternative solution.

**Additional context**
![image](https://user-images.githubusercontent.com/106010033/177459751-53105ba5-3ea1-419f-afcb-4301b0d2accd.png)

**Comment by veselink1** [comment]
Thanks for reaching out. The Microsoft Store handles licensing, payments, updates, package verification and signing, reviews, discoverability for me, and if I have to do all of these myself the app will probably not have any work done on it for a few months. Hope you understand. 

I really want to make this work though, as I've received multiple requests from people who cannot access the Store for whatever reason. I am working on a middle-ground solution that would allow a purchased license to be 'exported' and loaded onto another machine without access to the Microsoft Store.

**Comment by kohennigs** [comment]
Hi! 

same for me: MS Store is blocked/ not available. But i realy like FancyWM! 

It would be fine for me to buy FancyWM to support the dev(s). Hoping it s ok for your to use at work.

Kind Regards
Kai

**Comment by dellambrogio** [comment]
Same here. I would like to purchase, but I can't. Please implement the middle ground solution!

**Comment by veselink1** [comment]
FancyWM is open source. Happy holidays.

**Comment by veselink1** [comment]
Pre-built binaries will be provided soon.

**Comment by kohennigs** [comment]
What good news! Thanks and happy holidays!
