### ISSUE TITLE
Have Rule for Desktops

### ISSUE THREAD

**Issue by LegitCamper** [FancyWM/fancywm#115]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In the "Rule" Section it would be nice to have a desktop section, so it won't tile any window in Desktop 3. I frequently have games and game launchers in a separate desktop and it would be nice to have a rule to just leave those windows alone without having to black list all of their names.

**Describe alternatives you've considered**
I am not sure. I think this is the simplest way rather than entering each application name individually.

**Additional context**
![image](https://user-images.githubusercontent.com/28969132/180109711-9d07192e-15ac-446c-a8c2-ab170b7dbfea.png)

**Comment by veselink1** [comment]
This is such a great idea!

**Comment by incorrigible7** [comment]
I, for one, have my own spot for Steam on my third monitor right above Discord and silently (not so silently) curse those other companies that enforce their pitiful excuse of a launcher to run... But seconded. Sounds useful. 

Would desktop-specific saved panel layouts fall under this category as well? Oh, someone already mentioned that elsewhere, more or less. I'm unfamiliar with when ticket calling is appropriate, so I'll just leave it at that.
