### ISSUE TITLE
Window resize doesn't happen until focus is moved

### ISSUE THREAD

**Issue by willthong** [FancyWM/fancywm#120]
**Describe the bug**
Window resize keyboard shortcut pressed, but actual resize doesn't happen until window focus is moved.

**To Reproduce**
1. Enable Direct Mode keyboard shortcuts
2. Enter Direct Mode window resize keyboard shortcut (``Alt`` + ``Ctrl`` + ``h``)

**Expected behavior**
Window should get narrower. Instead, it remains the same size. However, if I do the following, the window resizes:
1. Enable Direct Mode keyboard shortcuts
2. Enter Direct Mode window resize keyboard shortcut (``Alt`` + ``Ctrl`` + ``h``)
3. Move focus to a different window (``Alt`` + ``k``)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2: 64 bit

Thanks!

**Comment by veselink1** [comment]
Thanks for reporting.

**Comment by ariccb** [comment]
Yes, I'm having this issue as well. I have the keybinding set to use without Activation Hotkey, but it still requires me to move the focus to a different window before it will resize.

**Comment by ericreeves** [comment]
Also having this problem!

- OS: Windows 11 64-bit
- 22H2 (Build 22621.819)

**Comment by ericreeves** [comment]
FWIW, This does NOT happen if I trigger the Activation Hotkey and then hit the resize key.  It only happens if I either have "Use Without Activation Hotkey" enabled and try to use it without popping the Activation Hotkey first OR if I trigger it using AHK via the fancywm.exe CLI command.

**Comment by SwarnaD** [comment]
This is also the case when using functions from AutoHotkey scripts, like `Run fancywm.exe --action IncreaseHeight`. Need to move the focus for it to take effect.

**Comment by javesar** [comment]
Yes I can confirm the same issue only when using without the activation hotkey. If you're using it with the activation hotkey, the function works as expected. 

OS: Windows 11 64-bit, 22H2
Fancy WM version 2.11.2.0
