### ISSUE TITLE
Unlocking device with multiple monitors results in FancyWM closing

### ISSUE THREAD

**Issue by DaJoTo** [FancyWM/fancywm#134]
FancyWM crashes after device gets unlocked - Win11

1. Multi monitor arrangement
2. Set out some windows
3. Allow device to lock
4. Unlock device
5. See FancyWM become unresponsive then close

**Expected behavior**
It can restore itself and managed windows when unlocking a device connected to another monitor

**Desktop (please complete the following information):**
 - OS: Win 11 Pro
 - Version 21H2

**Additional context**

Program is not producing exceptions or any crash logs, opening the UI you will see it become unresponsive and then it just closes. If you leave it long enough without opening the UI the icon will just disappear from the system tray.

**Comment by DaJoTo** [comment]
Just an update to try and give more detail on this issue.

I noticed that if the device is locked only briefly this problem doesn't occur, there is a bit of shuffling around while the monitor reconnects but it recovers all the window positions nicely.

If it's left locked for a longer period then it appears to arrange all the windows on the main monitor and becomes unresponsive. Once it's unresponsive (determined by trying to access the UI) the windows maintain their shapes but no snap to size when moved.

**Comment by DaJoTo** [comment]
So with the recently updated app, it now occasionally crashes and leaves a log. It is failing to find an appropriate location for multiple windows. There is often a 1-2 second delay in the monitor reconnecting, so I'm going to assume it's attempting to resume before the monitor is present. Not sure if this can be handled, like an attempt & wait pattern with a timeout?

**Comment by craiggwilson** [comment]
This happens for me as well. I have a number of crash logs, only one of which seems to show an exception, but the reset are labeled as crashes as well...
[fancywm-crash-20221017T135250.log](https://github.com/FancyWM/fancywm-issues/files/9824053/fancywm-crash-20221017T135250.log)
[fancywm-crash-20221017T150631.log](https://github.com/FancyWM/fancywm-issues/files/9824054/fancywm-crash-20221017T150631.log)
[fancywm-crash-20221017T181650.log](https://github.com/FancyWM/fancywm-issues/files/9824055/fancywm-crash-20221017T181650.log)
[fancywm-crash-20221018T104237.log](https://github.com/FancyWM/fancywm-issues/files/9824056/fancywm-crash-20221018T104237.log)
[fancywm-crash-20221018T125206.log](https://github.com/FancyWM/fancywm-issues/files/9824057/fancywm-crash-20221018T125206.log)
[fancywm-crash-20221018T153842.log](https://github.com/FancyWM/fancywm-issues/files/9824058/fancywm-crash-20221018T153842.log)
[fancywm-crash-20221019T152207.log](https://github.com/FancyWM/fancywm-issues/files/9824059/fancywm-crash-20221019T152207.log)

**Comment by GTonehour** [comment]
Just for reference: may be solved with the solution suggested in https://github.com/FancyWM/fancywm/issues/236.
