### ISSUE TITLE
Can not uncheck "Run automatically at system startup"

### ISSUE THREAD

**Issue by melonedo** [FancyWM/fancywm#136]
**Describe the bug**
The choice, "Run automatically at system startup", can not be unchecked. If I click it, it will flag as off for a few microseconds, then flag as checked again.

**To Reproduce**
1. Open the main menu;
2. Click the ✅ of "Run automatically at system startup";
3. It remains checked.

**Expected behavior**
The option be unchecked.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 21H2

**Comment by anodynos** [comment]
Same here, on 3 Windows 10 22H2 19045.2728 machines.

The most weird thing is I can't find it anywhere even with [Autoruns](https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns) to disable it manually.

**Comment by melonedo** [comment]
> Same here, on 3 Windows 10 22H2 19045.2728 machines, running FancyWM 2.11.2.0 both as Admin or normal user.
> 
> The most weird thing is I can't find it anywhere even with [Autoruns](https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns) to disable it manually.

I recently discovered in Windows Settings->Applications->Startup (approximate translations from Chinese) there is  an option to disable FancyWM's auto-startup.
