### ISSUE TITLE
Make "Move windows by holding Alt" key configurable

### ISSUE THREAD

**Issue by lubosmato** [FancyWM/fancywm#140]
**Is your feature request related to a problem? Please describe.**
This new feature is awesome however it makes user unable to use multicursor select in text editors.

**Describe the solution you'd like**
Alt key could be configurable in settings so user could change this key. Eg. to `Left Ctrl + Left Alt`.

**Describe alternatives you've considered**
Disable "Move windows by holding Alt".

**Additional context**

**Comment by sim590** [comment]
It also makes the user unable to box select in some applications like in the Windows Terminal...

**Comment by lubosmato** [comment]
Duplicate of #150
