### ISSUE TITLE
Activation keybinding not working.

### ISSUE THREAD

**Issue by iagonunez** [FancyWM/fancywm#142]
The activation keybinding is not working on Windows 11. I have tried to change it to all the possible alternatives and it does not work either. Tiling works but it is no way to use the keyboard to change the layout or move the window

 - OS: Windows 11
 - Version 22H2

**Comment by veselink1** [comment]
Thanks for reporting. Can you please indicate which version of FancyWM and whether this happened after a software update (FancyWM or Windows 11)?
