### ISSUE TITLE
Feature Suggestion: Close windows in stacked layout by clicking the middle mouse button

### ISSUE THREAD

**Issue by jweickm** [FancyWM/fancywm#145]
**Is your feature request related to a problem? Please describe.**
The tab overview of the windows when stacked is strongly reminiscent of the tab management in internet browsers. I like that I can close a window by clicking the little `x` in the corner. But sometimes it is hard to click. 

**Describe the solution you'd like**
It would be amazing if we could also close the windows by clicking with the middle mouse on the tab, just like in most (all) of the popular browsers.

**Comment by veselink1** [comment]
Good idea, thanks for the feature suggestion.

**Comment by jweickm** [comment]
Glad you like it. Hope it's not difficult to implement.
