### ISSUE TITLE
Drag to reorganize stack tabs

### ISSUE THREAD

**Issue by whaaaley** [FancyWM/fancywm#148]
It would be nice to drag to reorganize stack tabs like in Chrome.
That's all, thanks!

**Comment by brizdotdev** [comment]
It would also be nice to have keybindings as well.

**Comment by veselink1** [comment]
@brizdotdev You can use the swap window keybindings. Activation, then Shift Left/Right moves the windows in tab groups. 

![image](https://user-images.githubusercontent.com/12015256/201596867-4b43a82b-9398-4040-8005-51af3bfa316c.png)

**Comment by Enderw12** [comment]
Not only drag to reorganize stacked windows, but to enable stacking too.
Also there is a problem with stacking:
While there is no other windows except stacked ones, every new window opened will be added to stack, instead of being displayed side by side.
