### ISSUE TITLE
"Move windows by holding Alt" breaks vscode multicursor feature

### ISSUE THREAD

**Issue by mataslib** [FancyWM/fancywm#150]
**Describe the bug**
Make the feature off by default. Alt is widely used by code editors for multicursor features (eg. vscode). With this feature on, vscode multicursor does not work! And I suspect there are a lot of users using vscode.

The feature must have come out recently, I didn't notice it and all of a sudden my vscode stopped working. I didn't suspect FancyWM at all, because everything worked fine before. 

I had found out this new feature by accident after reinstalling when I was solving other issue.

**Expected behavior**
Installing FancyWM doesn't break other software.

**Comment by rc-austinoneil** [comment]
I had the same issue while trying to do multicursor functions in VSCode / Obsidian.

**Comment by riotrah** [comment]
I think I see two action items out of this:

1. Consider re-enabling the splash screen on startup whenever any "major" or "disruptive" features come out
    - And therefore also introduce the alt drag (and any new disruptive features) feature into that splash screen

2. Allow changing the toggle method for that feature
    - eg using the middle mouse button etc
    - changing the modifier key etc
