### ISSUE TITLE
Moving windows between monitors says "No adjacent window"

### ISSUE THREAD

**Issue by willthong** [FancyWM/fancywm#157]
**Describe the bug**
I'm happily able to switch focus between monitors using shortcut keys for 'up' and 'down'. However, I can't can't move windows between monitors in the same way (it says "No adjacent window!").

**To Reproduce**
1. While on the upper monitor, press the shortcut key to move the window to the lower monitor (in my case, 'Shift' and 'j')

**Expected behavior**
Window should move to the display which is below my current display. Instead, it says "no adjacent window!".

**Desktop (please complete the following information):**
 - OS: Windows 10
 - App Version 2.11.0.0

**Comment by whaaaley** [comment]
I would like this as well. I ran into this today.
