### ISSUE TITLE
Move windows while holding Alt interferes with creating extra cursors by holding alt in VSCode

### ISSUE THREAD

**Issue by ariccb** [FancyWM/fancywm#162]
**Describe the bug**
When I have the option to move windows while holding alt (very useful) turned on, when editing in VSCode, i'm not able to create new cursors on multiple lines anywhere, usually done by holding alt and clicking with the mouse.

**To Reproduce**
1. Turn Option on for moving windows with Alt held
2. Open VSCode
3. Try to hold alt and click (not click-and-drag) to create new cursors on a different line
4. error - no cursors created.

**Expected behavior**
I would expect that simply "Clicking", you'd be able to produce an extra cursor. I'm hoping that the FancyWM "Move windows while holding Alt" could wait for a DRAG instead of simply a click to activate.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version [e.g. 22000 21604-1628 64-bit]

**Comment by mataslib** [comment]
Well, you can spawn more selections by alt dragging in vscode, don't know how you would discriminate between these two cases.
