### ISSUE TITLE
Remove/Toggle FancyWM Floating Bar from Showing

### ISSUE THREAD

**Issue by jacobckelly** [FancyWM/fancywm#163]
**Is your feature request related to a problem? Please describe.**
Not a problem per say, but the FancyWM floating bar is annoying (and quite small at high resolutions).

**Describe the solution you'd like**
The ability to remove the FancyWM bar from showing, or to only show it from a key combination. The bar respecting windows scaling % might also be appreciated by others who do use the bar.

**Describe alternatives you've considered**
I looked for the option to do so, couldn't find it, so apologies if I missed it.

**Additional context**

**Comment by whaaaley** [comment]
![image](https://github.com/FancyWM/fancywm/assets/7419947/d8e7e39c-ccb5-4625-a9a5-ff60d5f83070)

Alternatively I would love to have something like this that could always be present. I really don't enjoy invisible UIs that appear. Always on would be great!
