### ISSUE TITLE
Building FancyWM as described does not work: hard coded file paths & missing `Resources` namespace

### ISSUE THREAD

**Issue by ckolumbus** [FancyWM/fancywm#168]
**Describe the bug**
Trying to build FancyWM as described in the README does throw build errors

**To Reproduce**
1. clone fancywm recursively, i used `git clone --branch v2.11.0 --recursive https://github.com/FancyWM/fancywm.git` to get a release source code version
2. Open the `fancywm.sln` in VS2022
3. Build the `Debug` Configuration via `F6`

**Expected behavior**
FancyWM build finishes successfully

**Actual behavior**
two types of build errors occur

1. `C:\Users\Veselin\Desktop\Icon.png` not found in `winman\src\Winman\WinMan.csproj`  : Solution? Replace the entry with `..\..\Resources\Icon.png`
2. Many compiles of source files fail with `CS0234 The type or namespace 'Resources' does not exist in the namespace 'FancyWM'`. Example `fancywm\FancyWM\App.xaml.cs`. I tried removing the `using FancyWM.Resources` reference, the build seems to succes for some files, but more specific references to `Resources` exist e.g in `fancywm\FancyWM\MainWindow.xaml.cs` where there is another line with `using Strings = FancyWM.Resources.Strings;`

I'm not sure why this happens: wether I'm missing something in my build environment or a configuration. Any help would be appreciated get this going!

**Desktop (please complete the following information):**
 - OS:  Windows 10 22H2
 - OS Build:  19045.2364
 - FancyWM Version: source code tag `v2.11.0` and also `main`

**Comment by veselink1** [comment]
Fixed a while ago, forgot to update.
