### ISSUE TITLE
Bug: Cortana popup every time using display desktop function

### ISSUE THREAD

**Issue by MisteryMonster** [FancyWM/fancywm#174]
**Describe the bug**
Cortana window will popup every time when Show desktop function recover window & panel.
**To Reproduce**
1. using shortcut shift+win+D to show desktop
2. press it again to recover, Cortana show

**Expected behavior**
No Cortana
**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10 22H2
 - OS Build: 19045.2486
 - FancyWM Version: 2.11.2.0

**Additional context**

**Comment by veselink1** [comment]
Apart from having FancyWM disable Cortana, I am not sure there is much else actionable.
