### ISSUE TITLE
Auto-focus on desktop change

### ISSUE THREAD

**Issue by 1MoreRaiday** [FancyWM/fancywm#175]
Its very frustrating to click windows every time i change desktop.

**Comment by 1MoreRaiday** [comment]
Alternatively there can be a function to auto focus window under cursor

**Comment by veselink1** [comment]
Just to confirm, are you seeing this when switching to a virtual desktop (Switch to desktop N in Settings) or when moving a window to a virtual desktop (Move to desktop N). 

Switch to Deskto N should focus the topmost window on that desktop. Move to Desktop N should keep focus on the moved window. 

In any case, this sounds like a bug, but I am not directly able to reproduce it so asking for clarification.

**Comment by bogdan-calapod** [comment]
Just for the record, the `Switch to desktop N` shortcut from settings doesn't work for me on the latest Windows 11 2261 (22H2)

**Comment by veselink1** [comment]
Closing as cannot reproduce the original bug.

**Comment by DinMon** [comment]
I don't know if this help, but I created a release with the fix https://github.com/DinMon/fancywm/releases/tag/v2.18.2.3-combined-focus-fixes
