### ISSUE TITLE
Pre-built binaries 

### ISSUE THREAD

**Issue by kohennigs** [FancyWM/fancywm#177]
Hi! 

May it be possible to provide the prebuild binariey like said in Isse 110?

Or did i just not the the place where they are? .. than GREAT SORRY! 

Thanks a lot  and kind regards

      Pre-built binaries will be provided soon.

_Originally posted by @veselink1 in https://github.com/FancyWM/fancywm/issues/110#issuecomment-1362068804_

**Comment by kohennigs** [comment]
> @kohennigs You can get it on Windows Store ;-)

That was the initial problem issue #110 mentioned above : 
no access to the store. 

And i was happy to read that this problem might solved.

**Comment by kohennigs** [comment]
Hello! 

Any news about that topic?

Kind Regards,
Kai Hennigs

**Comment by KaKi87** [comment]
Hello,

Any news on this ?

Thanks

**Comment by berot3** [comment]
I can't login on AppStore on my company laptop. So that means I can only download and install actual free apps (no IAP). So this would be really nice to have!

P.S.
A portable version would be nice too 😅🎈

**Comment by KaKi87** [comment]
I finally found out two ways to install it without the Microsoft Store :

1. Downloading the APPX file from [store.rg-adguard.net](https://store.rg-adguard.net/) by pasting the Store link (https://apps.microsoft.com/store/detail/9P1741LKHQS9) and clicking the latest version (`2.11.2.0`) ;
2. Downloading the APPX file from the open source [Fluent Store](https://github.com/yoshiask/FluentStore) app.

**Comment by kohennigs** [comment]
Hi there! 

From my point of view, our IT department will not be happy with the solution above ;-) 

(Just replace the M$ App Store with site-x that does magic with the stuff from M$ Store. Sorry, no front, but
it sounds not appropriate for our company environment. )


really hoping for the bins promised 2022 :

  Pre-built binaries will be provided soon.

Kind regards
Kai

**Comment by KaKi87** [comment]
Note that since the maintainer built the app to be distributed in the Microsoft Store, those binaries would likely be APPXs anyway.
You should get comfortable in getting less EXEs and more APPXs in this UWP era.

**Comment by kohennigs** [comment]
😆👍 

Ok , Thanks for this clarification! 

Wasnt aware of that. 🙏

**Comment by veselink1** [comment]
First build available here: https://github.com/FancyWM/fancywm/releases
Stil lhaven't figured out how best to package it all up. https://github.com/FancyWM/fancywm/releases/tag/v2.11.3-rc is just the zipped build artefacts from the CI job.

**Comment by kohennigs** [comment]
Hi! 

Cool, its going on here! Thank you!

First build is working for me! 

Not sure if the ignored autostart is not working only on my machine.

Going to check and test. Now i have version jump from i think 2.8 -> 2.11
