### ISSUE TITLE
Settings: Keybindings changes to <none> are not persisted

### ISSUE THREAD

**Issue by anodynos** [FancyWM/fancywm#178]
**Describe the bug**

Keybindings are not saved when they are cleared (i.e set to `<none>`)

**To Reproduce**
1. Clear a keybinding, ie. set to `<none>`
2. Change to another screen, eg Rules
3. Go back to Keybindings
4. The keybinding that was cleared, is back to previous value.

Alternatively
1. Clear one or more keybindings, ie. set to `<none>`
2. Set another adjacent keybinding (so you can see it) to some/same value (not `<none>`)
3. The previously cleared keybinding(s) are back to previous values.

**Expected behavior**
The value `<none>` should be persistent.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OS Build: 22H2
 - FancyWM Version: [e.g. v2.11.2.0]
 -

**Comment by TheSast** [comment]
You can temporarely get around this bug by setting all unwanted bindings to the same key (e.g. 'T').
Then to not have that key being used either: choose a mapping that you use, set it to the temp key ('T'), and set it back to the key you used beforehand.

**Comment by pingarelho** [comment]
This bug was never fixed.
