### ISSUE TITLE
Customisable activation hotkey

### ISSUE THREAD

**Issue by illettante** [FancyWM/fancywm#181]
It could speed manipulating windows up considerably if the activation hotkey were able to be customised.  

I use Windows Powertoys (although this could also be achieved in AutoHotKey) to remap my caps-lock key to a "virtual key" unused designation, the PA1 key (extant from the IBM 3270 122 key keyboard). It would be much faster if I were able to designate this as the activation hotkey; users would be able to use FancyWM without needing to move their left hand from the home row. 

I've considered just remapping the capslock key to send the default Ctrl+Win activation key, but I'm not sure if the Ctrl+Win shortcut might conflict with other things. I haven't found any yet, but the fact that Windows has the Ctrl+Alt+Shift+Win shortcut hardcoded to several obscure functions was why I went with a virtual key in the first place, to avoid the possibility of obscure conflicts entirely.

As an extension of this, it would be extremely useful (but probably out-of-scope) to allow the hotkeys to be mapped to two simultaneous non-modifier keys. This would allow the virtual key to be used in direct/universal hotkeys, satisfying users who prefer the direct key-chord shortcut-based approach *and* users who prefer the Emacs/RatPoison style activation-hotkey/prefix key approach.

**Comment by veselink1** [comment]
> allow the hotkeys to be mapped to two simultaneous non-modifier keys

Having more ways to define hotkeys does sound nice, however, I'm not sure how simultaneous key presses of non-modifier keys could work in practice, since the focused application would be free to process those key events (e.g. you might have Q+W set up as a hotkey, but if you have MS Word focused, what should it do with the key press events).

**Comment by riotrah** [comment]
@illettante I'm going to just guess that one of your use cases for capslock as a "hyper" key is for vim-style `hjkl->arrow keys`+ bindings? 

If so, what I've ended up doing is using `Kanata` (switched from `AHK`) to bind capslock to all modifiers, but [used AHK to unbind all of the useless "ad/bloatware" MS bindings](https://gist.github.com/riotrah/069c82891491a9a0829a6b5e0f67fe18#file-capslock-hyper-vim-ahk-L102-L162).

It's not an answer to your question, but it might open you up to a more typical hyper key setup, or allow you to bind fancywm activation key to caps lock or something
