### ISSUE TITLE
high cpu/gpu usage

### ISSUE THREAD

**Issue by majidaldo** [FancyWM/fancywm#182]
**Describe the bug**
High GPU usage by Desktop Window Manager in my case. I set program graphics affinity to the GPU.

**To Reproduce**
1. open fancyvm such that the application stays in the system tray. low gpu on Desktop Window Manager
2. open the fancyvm app from tray. high gpu.
4. close (not quit) . high gpu still.
5. exit/quit. low gpu.

can repeat.

**Desktop (please complete the following information):**
 - OS: 10
 - FancyWM Version: 2.11.2.0

**Additional context**
restarting fancyVM fixes the problem...until it becomes a problem again.

**Comment by majidaldo** [comment]
repro update

**Comment by veselink1** [comment]
Following the steps given, I cannot exactly reproduce the issue. I can see GPU % utilization go up from 2% to 3% after FancyWM is started. Opening FancyWM Settings and closing it, utilization is again ~3%.

I do not see an unexpected increase in CPU usage either. Can you please provide the numbers that you are seeing? Thanks.

**Comment by majidaldo** [comment]
> 
sorry. the reproducibilty is hard to track down. but i notice high gpu perhaps not immediately after starting the fancywm. still, if i notice high gpu, steps 3-4 are perfectly reproducible.
