### ISSUE TITLE
Despicable: FancyWM author ist aking down reviews on Windows Store!

### ISSUE THREAD

**Issue by anodynos** [FancyWM/fancywm#183]
I had a 5 Star review on Windows App Store, because I really liked what the project does. I was really praising the project and its potentials, and had something like a review of its best features. But I was also mentioning that "it rarely crashes, I will come back".

It struck as odd that **all other reviews disappeared** after my favorite review. As far as I remember there were 5-10 reviews before mine. But what could I do then?

After using it for several weeks, I realized it crashes too often to be trusted. So I updated my review with a 3-star and that problem exactly on the title. 

My review was immediately taken down, in minutes!

It seems its not only the program that cannot be trusted, but also its author(s). 

Shame. 

PS: I'm switching to https://github.com/microsoft/PowerToys which comes from Microsoft and looks promising!

Screenshots of my now deleted review, still cached on my local Windows Store. Clicking on it takes you to empty page!

![2023-04-05 14_06_35-Microsoft Store](https://user-images.githubusercontent.com/856453/230065883-8a3ebf48-a17d-412d-a71b-36576326e93c.png)

![image](https://user-images.githubusercontent.com/856453/230067199-3f2da878-5880-4211-93d0-1e7acaf47fe4.png)
![image](https://user-images.githubusercontent.com/856453/230067352-694a2b9a-337d-4713-8e54-3216f64f3261.png)![image](https://user-images.githubusercontent.com/856453/230067306-ee18e93e-866c-47f7-b7d0-877dc790ab11.png)

**Comment by veselink1** [comment]
This is really sad, but I assure you I am not taking down reviews. I wouldn't do that as it is indeed dishonest and I also don't have the power to do that - the Microsoft Store developer platform provides no such option as far as I'm aware. 

The only thing I have concluded is that the Microsoft Store developer experience needs a lot more work. 

I'm sorry your experience has been subpar.

**Comment by veselink1** [comment]
I understand. There's really nothing I can do however and I don't plan on chasing Microsoft support to see why this review is not visible, because I very much doubt that would be productive.

I can only say that I'm not surprised, knowing the state of the developer experience and how many times it's been broken for me.

Taking the stance that you've decided to take, guilty until proven innocent, means any course of action can now be misconstrued.

**Comment by anodynos** [comment]
I didn't say you are guilty, I said I have serious doubts, due to evidence. In any case, why did you close the issue?

Here's some screenshot from my laptop that still has a cache of previous reviews.  

![image](https://user-images.githubusercontent.com/856453/230070464-19415640-5b04-4ee0-93c9-a9260bb61920.png)

**Comment by veselink1** [comment]
Changing the title to reflect reality, I don't need to tolerate this and I also don't need to be providing "beef" to my claims or engaging in this discussion.
