### ISSUE TITLE
Screen Gap

### ISSUE THREAD

**Issue by hustea** [FancyWM/fancywm#184]
**Screen Gap would be good!**
Let's assume that i use some widgets and i want to see them as well as my programs, but i can't set it up.
When i use the Window Gap, it looks terrible and there is too much space.

**What does Screen Gap do and how can you achieve it:**
Screen Gap adds a margin outside on all sides so this way you can add margins seperately outside and inside. 
You can achieve this by overriding the screen size and position property (by Offset).
Or you can have a rect/bounds variable called "Workspace" and you can add padding to it
Pseudocode: ` RECT Workplace = { x + padding, y + padding, width - (padding * 2), height - (padding * 2) }; `

I included some pictures of how Window Gap and Screen Gap affects (what can you achieve using current VS my modification)

Using Window Gap:
![image](https://user-images.githubusercontent.com/58888959/230933834-e2537351-b3d5-488a-8fef-e5700c077a02.png)

Using Screen Gap:
![image](https://user-images.githubusercontent.com/58888959/230934645-5f51234f-9433-44d5-887b-0dab7027daa9.png)

**Comment by ngeraks** [comment]
Also I would suggest a dynamic/static screen gap switch. 
Dynamic would be something like: single window - gap is 200 px, two windows - 150 px,  4 windows (suddenly you need more space) 50 px. All this could be made configurable (which I presume will require a lot of effort).
