### ISSUE TITLE
Multiple tiling mode (change where new windows would launch)

### ISSUE THREAD

**Issue by SteveFour** [FancyWM/fancywm#185]
**Is your feature request related to a problem? Please describe.**
It usually require extra effort to rearrange windows if when launched, the windows are not in the desired positions.

**Describe the solution you'd like**
A way to make this less anoying is to allow multiple tiling mode/options, that can change where and how new windows launch.
Example:
Instead of the default launch behavior, which is allow windows to stack horizontally
![image](https://user-images.githubusercontent.com/79463793/231706516-c9817e18-ac8e-4e0b-838e-340e5e2292e6.png)
Which must require extra step to rearrange

My preference for laptops is to have two windows side by side, and the third and onward windows when launch will be stacked to the right
![image](https://user-images.githubusercontent.com/79463793/231706182-2c757108-a2f0-411f-b815-f62f17f3adb6.png)

Some other people like to use golden ratio tiling
![image](https://user-images.githubusercontent.com/79463793/231708632-69c14103-0fa6-49f9-986b-61a4114fd726.png)
(This make sense on a large display and not on my laptop display)

Having these options, it is easier to expect where windows will launch, and easier to rearrange windows, because the layout is already there, you just need to drag it

**Describe alternatives you've considered**
Create a limit for windows width in case width per app is smaller than that limit, new windows will launch in float mode, but float mode has the annoyance that the app not automatically snaps when we clear space for it/move to different desktop (this should be another feature/bug request)

**Additional context**
Also please allow other panel to be inside stack panel. Then when a new app launch and not having enough place to fit the app in, either (1) group all app group into a stack panel and launch new app in stack panel mode. OR if not, (2) launch the new app in new blank desktop.

**Comment by ngeraks** [comment]
Yup,  just determine if a window is selected then the new window will split the current selected window, if width is more than height -> vertical split, if height is more than width - > horizontal split. Like in pop OS

**Comment by veselink1** [comment]
Sounds like a sensible suggestion and something I've explored a bit before, but never got round to fully implementing. The main reason being that I would like to keep any changes backwards compatible. I don't want the next FancyWM version to have a completely different way of doing layouts, unless it is made configurable (which is a lot more effort).
