### ISSUE TITLE
Placeholder layout on first open

### ISSUE THREAD

**Issue by whaaaley** [FancyWM/fancywm#188]
I pretty much use the same layout everyday. I have two screens and each screen has two stacks, one left one right. I would love to be able to have these stacks open automatically with no windows in them and also force any new windows to appear in any of these stacks.

It would be great to have a placeholder or fixed layout setting designer thing. Or even just a config we could modify to do something like this.

**Comment by veselink1** [comment]
This has been asked for before and while it definitely sounds like a nice feature to have, it also is very difficult to cram into the exisitng model of how FancyWM operates (where there are no predefined layouts other than horizontal/vertical).
