### ISSUE TITLE
Direct Hotkeys

### ISSUE THREAD

**Issue by riotrah** [FancyWM/fancywm#19]
**Is your feature request related to a problem? Please describe.**
Often frustrated when I must repeatedly repeat activation key for actions that are not either covered by their own hotkeys - it adds a frustrating cumulative delay. Primary example is when trying to traverse more than 2 windows/panels visually ( ie when I feel inclined to traverse windows via arrow keys vs alt-tabbing to a known window instead )

**Describe the solution you'd like**
I wish I could quickly just press `< hotkey modifier > + LeftArrow` 3 times, instead of `< activation key >, wait slightly, LeftArrow`  3 times.

This would entail, either per-action, custom "direct" hotkeys, for which an prior-pressed activation key is not required, or an entirely different opt-in hotkey model, that eschews the chorded activation approach altogether in lieu of traditional keyboard shortcuts. Another approach may be that certain actions, like window traversal ( actions involving direction keys for example ) support direct hotkeys whilst others do not, at your discretion.

**Describe alternatives you've considered**
Being more patient and less speed-oriented. 

Reframing how I conceive of window traversal in my head to application/window-based instead of visually/spatially, thus reaching for alt-tab instead of fancywm arrow key shortcuts.

**Additional context**

**Comment by Kermit** [comment]
It can work similar to Pop_Shell in PopOS. 
Meta + Shift should open windows management mode which should be ended after pressing Enter (to accept) or Esc (to cancel changes) or smth like that.

Anyway, +1.

**Comment by veselink1** [comment]
I have been contemplating what a good fix to this issue would constitute. I have previously evaluated the direct hotkeys and the activation hotkey approaches, and concluded that there are more benefits to the activation hotkey approach (mainly, once can safely assign hotkeys to all actions, without worrying about clashing with other applications). 

I understand the desire to have a quicker way of moving between windows specifically, but then also, the same could be said for any other action. I would be striving for a more general solution, perhaps configurable on a per-action basis. I do not have a clear plan yet though. 

@riotrah Thank you for opening this feature request. You seem to indicate that there is the necessity to wait after pressing the action hotkey. Under normal circumstances, that should not be necessary. The appearance of the popup is purposefully staggered, so as not to appear during quick hotkey presses. It is not necessary to wait before pressing the Left arrow key, for example. If that is not the case for you, I would consider it a bug. 

@Kermit Thanks for the suggestion. In general, I would prefer to stay away from having an editing mode. That is, in my mind, one of the features of FancyWM. I don't believe having a separate mode that you enter manually **and** leave manually is better in the average case. There have been suggestions in a comment on a different thread about having a continuous mode https://github.com/FancyWM/fancywm-issues/issues/14#issuecomment-998861089, which am currently experimenting with. Anyway, consider opening a feature request if you feel that there is something to be gained from having this editing mode. 

Thanks.

**Comment by lentsius-bark** [comment]
allow me to chip in on this one, you the fact that there aren't direct hotkeys, is the reason i won't be using fancyWM, my prefered way of working with a tiling manager is the ability to have tabbed workspace and quickly move from one to another, having to always press the activation key essentially means I'm wasting time on something that's meant to be faster than anything else.
@veselink1 it's fantastic to see that you're thinking of an elegant solution, I'll keep an eye out on this issue to see where it goes!
I don't want to come off as someone that comes in and complains so let me add that you've created something awesome, I loved FWM!

**Comment by veselink1** [comment]
Quick update: As of v2.4.0, users are able to set up custom hotkeys using AutoHotkey (in preview).

**Comment by veselink1** [comment]
Experimental in-app support for direct hotkeys is now available in v2.6.0.

**Comment by veselink1** [comment]
@paprocki-r Lightning bolt button next to the keybinding enables it. 
![image](https://user-images.githubusercontent.com/12015256/183299447-721621ce-7b35-42cc-a860-a27fad3a7942.png)
