### ISSUE TITLE
OLED auto-gap change/shift

### ISSUE THREAD

**Issue by ngeraks** [FancyWM/fancywm#190]
The title says it all. OLED TVs for computer screens are mainstreem now, even a lot of laptops started using oled screens. 
If window gaps can change automatically in a predefined way (or just window placement within those gaps) , 
fancyWM can have a sort of pixel-shifting effect. 
Say every few predefined seconds, windows can shift by a pixel (or a few) in a given direction e.g. dvd bouncing image.
This will be very useful for OLED users, without this functionality (like me, with my Gigabyte FO48U).

**Comment by majidaldo** [comment]
I don't see why this is something that's in the scope of fancywm.
Should be handled in os or better yet firmware

**Comment by ngeraks** [comment]
> 
Why should there be a program to handle the window placement at all, yeah?

**Comment by veselink1** [comment]
Sounds like a neat idea, but I'm not sure how this would eliminate burn in. I assume you mean shifting the window back and forth by a few pixels every few seconds. So every few seconds it moves out of position and back. Wouldn't that eliminate only some cases of burn in, where the movement amount is greater than the image that would case burn in? 

I don't have an OLED screen but if I did I would have probably had a screensaver configured. I think this is probably best solved in a separate tool.

**Comment by ngeraks** [comment]
This is supposed to be useful for static content, e.g. firefox tab titles/icons. When people use multiple of them, usually they stay constantly on screen, so many preventative measures do not activated (like screen saver). Many TVs implement static content detection, pixel shifting etc. many, however do not have this feature. 
If fancyWM can have a window gap of say 10 px, and my icons are a similar size, that static icon will get shifted over time, thus other pixels will take the load for a time. Again, think of the bouncing DVD logo.
