### ISSUE TITLE
Greyscale for non-focused Windows

### ISSUE THREAD

**Issue by phly95** [FancyWM/fancywm#191]
**Is your feature request related to a problem? Please describe.**
It might make it easier to focus if only the focused Window is in color, and all other Windows are black and white. An example on MacOS would be https://github.com/w0lfschild/GrayFocus

**Describe the solution you'd like**
Option to set background windows to black and white/grayscale

**Describe alternatives you've considered**
Setting all Windows to black and white via Windows accessibility, but I often want color for the main window.

**Comment by veselink1** [comment]
Sounds like a neat idea but unfortunately to the best of my knowledge there isn't an API in Windows that would allow you to do this.
