### ISSUE TITLE
Switch to desktop while moving a window

### ISSUE THREAD

**Issue by tgienger** [FancyWM/fancywm#193]
**Is your feature request related to a problem? Please describe.**
I would like the option to move a window to a new workspace (desktop) and switch to that desktop at the same time.

**Describe the solution you'd like**
A toggle on the "move" keybind section that asks if we would like to also switch to that desktop

**Describe alternatives you've considered**
I tried scripting it with ahk, but it fails work properly. I can only get it to do one or the other, not both even with a small sleep. and it would not do anything if i was in a text editor at the time of hitting the hotkey.

**Additional context**

**Comment by veselink1** [comment]
So you would like SwitchDesktopN (switch to N) and MoveDesktopN (move window to N) in one action? I would start by adding a new set of actions in `BindableAction`. You would also need to add text descriptions for those in `Strings.resx` for them to be visible in Settings. Then you can bind your keys and implement the dispatch in `MainWindow.ExecuteAction`.
