### ISSUE TITLE
Add a key to stack all windows

### ISSUE THREAD

**Issue by xuwei152** [FancyWM/fancywm#196]
It will be convenient to have a shortcut key to stack all windows when all windows are messed up like the pic below.  Otherwise, I have to stack one by one.
![stackallwindows](https://github.com/FancyWM/fancywm/assets/51861161/594a14e6-15e5-4cf2-8320-33d43433b942)

**Comment by TressaDanvers** [comment]
I am in agreement. In BSPWM I use Alt-M to switch to monocle mode, and all-windows-stacked in this WM is very similar to the behavior of monocle mode in BSPWM. With that said, It would be nice to see the ability to bind Alt-M in your application to "Stack/Unstack All Windows".
