### ISSUE TITLE
Windows shuffle and unstack when switching between virtual desktops

### ISSUE THREAD

**Issue by gabeusgong** [FancyWM/fancywm#198]
**Describe the bug**
When switching between virtual desktops my open windows will shuffle and unstack. I have tried using different methods to switch between desktops and I have also tried reinstalling FancyWM to no avail. My laptop is running Windows 11, though this issue is not present on my PC which is running Windows 10. I've been experiencing this issue for a few weeks now.

**To Reproduce**
Switch between virtual desktops using hotkeys, mouse gestures, or any other method. They always unstack.

**Expected behavior**
Windows remain unchanged and stacked when switching between virtual desktops.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - OS Build: 22621.2428
 - FancyWM Version: 2.11.2.0

**Additional context**
When running FancyWM after I close the program, I am always met with a pop up displaying something along the lines of "Some features will not be available as your device is out of date." I have tried running Windows updates several times but this has also not solved the issue.

**Comment by rmvermeulen** [comment]
I have the exact same issue. Whenever I switch desktops everthing unstacks.
I do also get the pop up: 
![image](https://github.com/FancyWM/fancywm/assets/14540163/eb7cec0a-9960-42e4-bf15-ce7848636f48)

- FancyWM Version: 2.11.2.0
- Windows 11, build 22621.2715.

I use virtual desktops extensively, so this makes the entire app unusable for me. Possibly related: sending/switching to virtual desktops also doesn't work. Maybe FancyWM is not 'detecting' that there are other desktops or something.
