### ISSUE TITLE
Allow Alt+[number] as keybinding

### ISSUE THREAD

**Issue by CoenKonings** [FancyWM/fancywm#199]
**Is your feature request related to a problem? Please describe.**
I switch Virtual Desktops often, especially if I'm away from home and working on my laptop which has a small screen. I want to be able to use the hotkey without activation, and I prefer using Alt+1 to switch to desktop 1, Alt+2 to switch to desktop 2, etc., and use Alt+shift+1 to move a window to desktop 1, etc. Currently, Alt+1 is not allowed as a hotkey - it shows up as just "Alt".

**Describe the solution you'd like**
I'd like to be able to set Alt+1, Alt+2, etc. as hotkeys in settings.

**Describe alternatives you've considered**
I've considered using Alt+q, Alt+w, Alt+e, etc., or Alt+a, Alt+s, Alt+d, etc., but these hotkeys run into issues with hotkeys in other programs.

**Comment by YuzhenQin** [comment]
![图片](https://github.com/FancyWM/fancywm/assets/59137898/1759168b-05af-4815-8738-f084233154af)

**Comment by CoenKonings** [comment]
It's working for me now too.
