### ISSUE TITLE
Scripting / Extensibility

### ISSUE THREAD

**Issue by riotrah** [FancyWM/fancywm#20]
**Is your feature request related to a problem? Please describe.**
No direct problem per se. Just a thought.

**Describe the solution you'd like**
I've tried most (active, some inactive) Windows TWMs. 

Some of them offer scripting in the original language of implementaton, to offer things like custom layouts with custom insertion logic or auto BSP support ( without having to embed an interpreter or create some kind of DSL ). 

Others might publish streams or NamedPipes for other applications to subscribe to events from, allowing them to create responsive applications "on top of" them. Eg a custom status bar, etc.

Whether this would benefit a closed-source TWM like FnacyWM is unclear to me, as it depends on what you, the author, consider its success criteria and other long-term goals. I posit, that it adds extended surface area and thus responsibility for you to support, but may be a value-add, and expanded presence in the open source world, where FancyWM is currently somewhat present ( eg for shared community extensions / layout engines etc ).

**Describe alternatives you've considered**
Requesting you, the author, to implement features for me through this issue tracker.

**Additional context**

**Comment by veselink1** [comment]
v2.4.0 introduces experimental scripting support. Users can now use `fancywm.exe --action <Action>` to execute one of the following actions. 
- PullWindowUp
- CreateHorizontalPanel
- CreateVerticalPanel
- CreateStackPanel
- MoveFocus<Direction>
- Move<Direction>
- Swap<Direction>
- Increase|Decrease<Width|Height>
- SwitchToDesktop<N>
- MoveToDesktop<N>
- ToggleFloatingMode

There is an new option under Settings > Advanced to create an AutoHotkey script template.

**Comment by riotrah** [comment]
Ah awesome, thanks for the work !! 

This also scratches the direct hotkeys itch, at least for those familiar/comfortable with AHK.

Perhaps in order to then support custom layouts ( which you could create a github tag for, or a community "Shared Layouts/scripts" repo for ), we would prob also need querying/reading FancyWM state in some digestible manner, so we can respond to it, or even events from FancyWM. Obviously this is potentially a huge undertaking depending on how state is represented under the hood.

In any case, I could imagine sufficient state read/query capacity, and then the capacity to directly "set" certain state ( like setting panel/window dimensions _directly_ in px or something, instead of repeated "increase height" statements ), would go a tremendous way for all kinds of customizability, and would prob solve #5 or #12 out the gate ( for AHK users at least ).

Thanks again!
