### ISSUE TITLE
How to update FancyWM?

### ISSUE THREAD

**Issue by javesar** [FancyWM/fancywm#207]
### Discussed in https://github.com/FancyWM/fancywm/discussions/202

<div type='discussions-op-text'>

<sup>Originally posted by **javesar** November 10, 2023</sup>
Hello, how do I update my FancyWM to the latest version? I've been tracking an issue reporting a bug that was resolved in v2.11.3 and I currently have v2.11.2</div>

**Comment by bogdan-calapod** [comment]
I think there needs to be another store release for the update to come through
