### ISSUE TITLE
Your donation button is broken :)

### ISSUE THREAD

**Issue by wired** [FancyWM/fancywm#214]
Tried to donate, but PayPal is giving me "This organization's page is broken." both with the button in settings and the button on GitHub.

![image](https://github.com/FancyWM/fancywm/assets/58193/51974462-fbfa-4014-b26f-34b46963ed7a)

**Comment by Kur0n3-112** [comment]
Yeah is a same :"(
Is a very util and cool gadget for windows

**Comment by sosafe-renan-magalhaes** [comment]
Same here. This is such a cool and important app for my workflow. I definitely want to support it 

@veselink1  Take our money!!! :D

**Comment by renantmagalhaes** [comment]
Same here. This is such a cool and important app for my workflow. I definitely want to support it

@veselink1  Take our money!!! :D

**Comment by veselink1** [comment]
Thanks all for the support. I've updated the link.
