### ISSUE TITLE
Release v2.11.3-rc contains v2.11.0.0 version

### ISSUE THREAD

**Issue by VladDae** [FancyWM/fancywm#217]
Downloaded [Release.zip](https://github.com/FancyWM/fancywm/releases/download/v2.11.3-rc/Release.zip) and [Source code (zip)](https://github.com/FancyWM/fancywm/archive/refs/tags/v2.11.3-rc.zip) from [release page](https://github.com/FancyWM/fancywm/releases/tag/v2.11.3-rc). 
Both contains v2.11.0.0 version. 

![image](https://github.com/FancyWM/fancywm/assets/25726492/01b111fd-4bb1-4bed-a362-58caaacf4e45)

**Comment by Bureaucromancer** [comment]
Not just a label issue - it's throwing the limited functionality error for me.
