### ISSUE TITLE
Ability to disable "Your version of windows is not supported" notifications

### ISSUE THREAD

**Issue by markpendlebury** [FancyWM/fancywm#218]
Since updating Windows 11 recently every time i start my pc i get the following message: 

![image](https://github.com/FancyWM/fancywm/assets/63231900/c5e1f842-a4f7-47b7-b910-aaf0778d407b)

I get that it's not supported, and i'm happy with that, but what i'm not happy with is being reminded about it each time i turn on my PC. I likve to have my applications boot silently. This is very annoying

If possible, add a "Don't show this again" check box or similar.

**Comment by matdave** [comment]
Also, what is triggering this? I just have Windows 11, which _should_ be supported.

**Comment by mahtaran** [comment]
@veselink1 Any update on this?

**Comment by veselink1** [comment]
Windows has an internal virtual desktop API which FancyWM tries to use. 

There is no public API equivalent, and the internal API changes frequently, including via Windows Update, which makes it hard, if not impossible, to support on Windows 11.

However the notification is should be made less frequent.

**Comment by markpendlebury** [comment]
I understand supporting windows 11 and it's virtual desktop component is a pain but I'm asking here for here is a simple "don't show this again" check box 



I've added a work around to this by simply removing the check on the build number that results in this notification for now, I know this isn't the solution but I'm happy to push a branch for those that want to build it themselves without this annoying message.
