### ISSUE TITLE
How to install the latest release 2.11.3

### ISSUE THREAD

**Issue by KirilOkun** [FancyWM/fancywm#219]
**Is your feature request related to a problem? Please describe.**
I saw that an issue i was having was fixed in rc 2.11.3.  I downloaded it from Github and unzipped the archive but not sure what's the best way to install it.

**Describe the solution you'd like**
Some kind of readme describing how to install an RC over the version installed from the app store.

**Describe alternatives you've considered**

**Additional context**

**Comment by seanawdish** [comment]
Same issue as Kiril
