### ISSUE TITLE
2.11.4-rc release still reports 2.11.0.0 & does not persist window configuration

### ISSUE THREAD

**Issue by jameslawfer** [FancyWM/fancywm#226]
**Describe the bug**
The latest 2.11.4-rc release still reports
- Version 2.11.0.0 in the About FancyWM page #217 
- "Your version of Windows is not supported!... You may experience limited functionality until your version of Windows becomes supported or until you upgrade to a stable release." upon startup #218 
- Hot plugging a monitor disassembles stack panels #129 
- Changing between workspaces/virtual desktops disassembles stack panels and resets window configuration

**To Reproduce**
1. Download the 2.11.4-rc release from Github
2. Launch and check 'About FancyWM' from the right click context menu from system tray
3. Create a FancyWM window stack and switch between desktops (Win + Tab or Ctrl + Win + <ArrowKey>) or hot plug additional monitor
4. Arrange FancyWM windows and switch between desktops or hot plug additional monitor

**Expected behavior**
- App to report 2.11.4-rc in the About FancyWM page
- Unsupported version of Windows popup to not be present
- Window configuration (including stack panels) should persist after switching back through desktops or hot plugging monitors

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise (22H2)
 - OS Build: 22621.3155 (Windows Feature Experience Pack 1000.22684.1000.0)
 - FancyWM Version: 2.11.4-rc

**Additional context**
N/A

**Comment by veselink1** [comment]
Thanks for reporting. The 3 tickets you've linked to are stil open? I will close this issue.

**Comment by jameslawfer** [comment]
@veselink1 No problem & thanks for reviewing. I opened a new issue as it was targeting the 2.11.4-rc release specifically, however the main new issue would be regarding the final point:
> Changing between workspaces/virtual desktops disassembles stack panels and resets window configuration
I couldn't find another issue referencing this, could we reopen the issue for this, or would you prefer a separate issue raised?
