### ISSUE TITLE
Defender is affraid of the last build

### ISSUE THREAD

**Issue by MoutonBinoclard** [FancyWM/fancywm#227]
Last version of Fancy WM 2.11.4rc let think Windows Defender that this is a trojan 
(About the zip file)

**Comment by veselink1** [comment]
That is curious. The diff between this version and the previous one is very small in terms of code. However 2.11.4rc is built using a newer .NET framework.

**Comment by MoutonBinoclard** [comment]
![image](https://github.com/FancyWM/fancywm/assets/77278792/8571d84c-8227-476c-aa67-17de4372af30)

**Comment by MoutonBinoclard** [comment]
very strange indeed, the strangest thing is after unziping, nothing was wrong...

**Comment by veselink1** [comment]
Couple of things:
- I cannot advise ignoring your Antivirus, as that might open you to other issues. 
- That being said, the releases artefacts on GitHub are checksummed, so at the very least, you can verify that the file you downloaded is actually the one you wanted and has not been modified. All you need to do compare the SHA256 with the one of the file you downlaoded, that would give you greater confidence, in your case Release.zip.sha256. Using PowerShell:
```powershell
Get-FileHash Release.zip
```
- There is always the chance that your computer/network is infected and files you download become infected with malware.

However, no antivirus is perfect. In the case of Defender, there is https://www.microsoft.com/en-us/wdsi/filesubmission which allows files to be submitted when there are false-positives, which I will do for the current releases.
