### ISSUE TITLE
Donation Link seems to be broken

### ISSUE THREAD

**Issue by peschu123** [FancyWM/fancywm#233]
**Describe the bug**
When I click "Sponsor" in the settings windows it calls an URL to paypal:
https://www.paypal.com/donate/?hosted_button_id=NKQ6DKGFVN7S2

The website says:
This organization's page is broken.

**Expected behavior**
Some possibility to donate money should come up.

**Screenshots**
![swappy-20240327_085212](https://github.com/FancyWM/fancywm/assets/29665959/296747de-2e42-4e91-b1b3-0c39677a4eac)

**Desktop (please complete the following information):**
 - OS:Windows 10
 - FancyWM Version: 2.11.4

**Additional context**
I would love to spend some money on this, it's not perfect, but a big improvement to just "all floating windows" and way better than fancy zones. I use swaywm on my desktop and windows often in a rdp session. It's really nice that the shortcuts from sway do not interfere with fancywm (at least "guest" not with "host")
Would be nice to have q to close/minimize windows.
Thank you for this nice application, saved me from insanity ;-)

**Comment by veselink1** [comment]
Thanks, hope it continues to be useful. I've updated the link.
