### ISSUE TITLE
`fancywm` command not recognized

### ISSUE THREAD

**Issue by mflova** [FancyWM/fancywm#234]
**Describe the bug**
After the `2.11.4` automatic update from the store, the `fancywm` command is not recognized within my system. I also tried reinstalling it from the store but nothing changed. How can I make it work? Thanks!

**Desktop (please complete the following information):**
 - Currently using Windows 10 Enterprise

**Comment by veselink1** [comment]
This is a bug in 2.11.4, so I have pulled the version from the Store. If you reinstall the application, you will get 2.11.3, which should work. I've fixed the bug in 2.11.5 which will be available in the Store in a few days (MS Store updates require review).
