### ISSUE TITLE
Installaion via Windows package managers like winget

### ISSUE THREAD

**Issue by Gorpokki** [FancyWM/fancywm#237]
**Is your feature request related to a problem? Please describe.**
Installing via the Microsoft Store does not open the ability to install fancywm with scripted/automated system setup through powershell or cmd

**Describe the solution you'd like**
Distribution via scoop, winget, and chocolatey
Or just winget

**Describe alternatives you've considered**
Grabbing the latest releases through Github and installing through Powershell is possible but not recommended. The readme does not mention why it isn't recommended.

**Comment by veselink1** [comment]
The reason it is not recommended to install the zip for now is that there is not automatic update check built in the app.

**Comment by veselink1** [comment]
```
winget install fancywm
```
works for me.

I've updated the README.
