### ISSUE TITLE
Remember group state

### ISSUE THREAD

**Issue by aolko** [FancyWM/fancywm#243]
**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**
It would be helpful to remember the group state when windows are removed from the group leaving only initial window (i.e. do not ungroup, only ungroup if all windows are closed)

**Describe alternatives you've considered**
Recreating a group manually, quickly becomes annoying.

**Additional context**
\-

**Comment by veselink1** [comment]
Does Settings > General  > Automatically collapse panels help with what you're looking to achieve?

**Comment by aolko** [comment]
> Does Settings > General > Automatically collapse panels help with what you're looking to achieve?

causes #245

**Comment by lesca** [comment]
+1

Hello, 

I think it's a good idea to remember the panel / group state. 

In a stack panel, it accepts one window when you create the stack, then I add a new window into it. Unfortunately, I clicked the maximize button, then the stack panel is gone. I have to create it again!

It would be great if it can remember the stack panel even if there is only one left. 

Additionaly, it would be better if FancyWM can remember the created panels even after computer restart. 

Regards,
Lesca

**Comment by veselink1** [comment]
> It would be great if it can remember the stack panel even if there is only one left.

There's an option in settings called "automatically collapse panels" which is on by default. When on, when a panel is left with just one window, the panel is destroyed.

**Comment by lesca** [comment]
> > It would be great if it can remember the stack panel even if there is only one left.
> 
> There's an option in settings called "automatically collapse panels" which is on by default. When on, when a panel is left with just one window, the panel is destroyed.

I turned it off, it looks good now.
