### ISSUE TITLE
Godot 4.2.2 doesn't show tooltips when FancyWM is running

### ISSUE THREAD

**Issue by micahboggs** [FancyWM/fancywm#246]
**Describe the bug**
When FancyWM is running the program godot version 4.2.2 (https://godotengine.org/download/windows/) does not show tool tips when hovering over toolbar icons. It functions properly when FancyWM is not running. Issue occurs even if I have a rule set to float the window (either by process name, or by windows class)

**To Reproduce**
Run Godot 4.2.2. hover mouse above any of the buttons.

**Expected behavior**
Hovering mouse over buttons in Godot 4.2.2 should show a tool tip after about half a second.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OS Build: 19045.4291
 - FancyWM Version: 2.12.1.0

**Comment by veselink1** [comment]
I've managed to reproduce this. I suspect Godot's tool tip mouse detection is not liking the FancyWM overlay. Other applications are not affected by this from what I can see.

This appears to be a Godot-specific issue. I do not see how FancyWM can fix it at present.

**Comment by coffandro** [comment]
Just wanted to comment, godot is similar to Chromium (at least for versions older than v3) so if an issue arrises on godot it might also occur on other chromium based applications
