### ISSUE TITLE
Borders and multi monitor support

### ISSUE THREAD

**Issue by markox92** [FancyWM/fancywm#248]
Hello,
Do you have plan to add custom borders function and also support for multi monitor?
Now I can move window only on selected monitor but I can't move it easy like CTRL+SHIFT+RIGHT from one monitor to another.

**Comment by veselink1** [comment]
Hi, can you please clarify why the existing keybindings for moving across monitors don't work for your use case? 
![image](https://github.com/FancyWM/fancywm/assets/12015256/73976d20-bebe-4aee-a599-e90e7555da0e)

Also, what is a "custom borders function"? Is that a border around the focused window that is permanently visible? If it is, I'm currently testing that and plan to put it in 2.14.0.

**Comment by markox92** [comment]
Yes I mean border around focused/active window, about move window across monitor for me does not work for some reason, I will must test this again....

**Comment by markox92** [comment]
This is what I mean

![Screenshot 2024-05-30 131830](https://github.com/FancyWM/fancywm/assets/159203552/b53ea24a-84a9-4643-a6b0-8612f4ea2515)


This will move window only in current monitor I think is better to move window across all monitor, this is how tiling should be works also windows default settings is also work on same way win + right for example moving focused window on across all monitors

**Comment by veselink1** [comment]
Borders added in 2.14.0.

**Comment by markox92** [comment]
Thanks...

**Comment by Rasie1** [comment]
I wish other monitors could be optionally treated as an extension of the current monitor and would get windows automatically. Aint got no time for moving stuff to other monitors manually
