### ISSUE TITLE
separate window padding to any side

### ISSUE THREAD

**Issue by httpassoca** [FancyWM/fancywm#249]
I have floating windows taskbar, so the windows get above the bar and I can't see it:
![image](https://github.com/FancyWM/fancywm/assets/49541181/5f3b285d-b0ea-41e8-9e9f-b612eba23567)
 
If I increase the window padding to 32 (maximum) I can see some of it
![image](https://github.com/FancyWM/fancywm/assets/49541181/7b8adbad-d3b0-4fc8-a056-32be0286accf)
But then the windows have a massive padding between them
A nice workaround would be configure just the bottom padding of the windows. And increase the maximum number.

**Comment by veselink1** [comment]
Hi, what is a floating windows taskbar? How can I enable and test it?
