### ISSUE TITLE
monocle mode 

### ISSUE THREAD

**Issue by executer9648** [FancyWM/fancywm#260]
**Is your feature request related to a problem? Please describe.**
fancywm doesnt support native monocle asside from full screening the app manuallyץ

**Describe the solution you'd like**
when you only have 1 window open that window is enlarged to fit the whole screen, my suggestion would be to have a selected screen that the same space once a shortcuts was pressed. and when pressed again it would return to the previous layout from before the monocle. this would be different from a simple full screening the window as only 1 window can be in this mode at once on each v.desktop.

**Describe alternatives you've considered**
right now im using the regular full screen mode its just that when i have 1 window in full screen and then open another one they are both not tiled, with this feature it would just replace the window that is in monocle.

**Additional context**
glazewm and komorebi have this feature if reference is needed.
fancywm by far surpasses them both

**Comment by b1scu1t** [comment]
Komorebi has it, GlazeWM does not, and the former has a somewhat buggy implementation of it. 

I suggest looking at BSPWM for a good idea.

You can already kind-of replicate the monocle layout in FancyWM by maximizing (not full-screen) the window. I can swap between multiple maximized windows just as like in a monocle layout, using the taskbar. The only caveat is that you must maximize each window yourself.

_And yeah, FancyWM is by far the most stable, 'just works' tiling WM for Windows. It is the only one that handles full-screen games correctly, and doesn't forcefully resize all windows (which breaks them)._
