### ISSUE TITLE
Subsequent commands while holding the key

### ISSUE THREAD

**Issue by Rasie1** [FancyWM/fancywm#262]
In i3 I usually hold Super and do multiple shortcuts at the same time (movement, moving windows to workspaces, etc). 
In fancywm I have to release the activation key between each shortcut

- this is not how shortcuts usually work
- releasing and pressing the key again takes a lot of time

Example workflow:
I'm peeking through workspaces, searching for a window. When I found it, I move it to workspace 1

I want to hold Caps Lock key and quickly press 1, 2, 3, ... until I find the window. Then I would just add shift and press 1. This could be lightning quick, but now I have to release caps lock every time. This makes it 2+ times slower

**Comment by Rasie1** [comment]
???

**Comment by b1scu1t** [comment]
> In i3 I usually hold Super and do multiple shortcuts at the same time (movement, moving windows to workspaces, etc). In fancywm I have to release the activation key between each shortcut
> 
> * this is not how shortcuts usually work
> * releasing and pressing the key again takes a lot of time
> 
> Example workflow: I'm peeking through workspaces, searching for a window. When I found it, I move it to workspace 1
> 
> I want to hold Caps Lock key and quickly press 1, 2, 3, ... until I find the window. Then I would just add shift and press 1. This could be lightning quick, but now I have to release caps lock every time. This makes it 2+ times slower

Hi. 
You can replicate that behavior by binding your activation key WITH your hotkey and activating 'Use without hotkey'.
It works just like i3WM and BSPWM this way.

![FancyWM_rzYNEOYeDF](https://github.com/user-attachments/assets/8e044f63-c1f5-4082-b8ae-a5f34b898543)
