### ISSUE TITLE
Support for Dwindle Layouts

### ISSUE THREAD

**Issue by TheAyes** [FancyWM/fancywm#283]
**Is your feature request related to a problem? Please describe.**
The feature is not related to a problem.

**Describe the solution you'd like**
I'd like to put emphasis on a new way of laying out windows. I know this layout from hyprland which is what I'm using privately. In a dwindle layout the split is determined dynamically with the W/H ratio of the parent node. If W > H, it’s side-by-side. If H > W, it’s top-and-bottom. It then simply places the window to the nearest anchor point.

**Additional context**
Link to the hyprland docs explaining the dwindle layout: https://wiki.hyprland.org/Configuring/Dwindle-Layout/

**Comment by veselink1** [comment]
Thanks for the suggestion I've not managed to find a video demonstrating how this works. I'm not really sure what the difference is between this layout and the setting Automatic Split Threshold = 2 (default in 2.14)? FancyWM will then split based on W/H ratio as you say.
