### ISSUE TITLE
Capslock as activation key doesn't work as advertised

### ISSUE THREAD

**Issue by JordanAnthonyKing** [FancyWM/fancywm#285]
**Describe the bug**
Using the caps lock key for the activation key advertises that the user can hold the key instead of just tapping, however this only works for  a single button press so for actions like moving across many windows you still have to repeatedly press caps+key.

**Expected behavior**
The user can hold caps and press any amount of keys as many times as they want, as they could with any normal modifier key they're used to.

**Comment by coffandro** [comment]
So the issue here is that caps lock triggers when shift is held so you can't go like shift+ something else´?

**Comment by coffandro** [comment]
same error occurs for me on 1.124

**Comment by JordanAnthonyKing** [comment]
> So the issue here is that caps lock triggers when shift is held so you can't go like shift+ something else´?

No, I mean that the following key sequence down’t work: `Caps down, left, left, left, caps up` only the first left is sent. `Caps down, left, caps up` works and I can repeat that process. Contrast this to the standard way of doing things:
`[Activation key down], [Activation key up], left`
