### ISSUE TITLE
Allow option to specify number of pixels when changing the window size via keyboard shortcut.

### ISSUE THREAD

**Issue by freddiehaddad** [FancyWM/fancywm#289]
It would be a huge quality of life improvement if we can specify the number of pixels to increase or decrease the window width or height by when resizing instead of it being an arbitrary amount.

In the configuration settings, add the option to specify the number of pixels to increase or decrease a window by when performing the action via keyboard shortcut. For example, I enter the value 20, then, when I resize a window, it will grow or shrink by 20 pixels in the vertical or horizontal direction depending on whether I'm increasing or decreasing the window size.

**Comment by veselink1** [comment]
Thanks for the suggestion. Quick question, do you think it makes sense to scale this by the monitor DPI? If you have a 4K monitor at 200% DPI, I feel it makes sense to apply 40px increase, however, want to hear opinions.

**Comment by freddiehaddad** [comment]
> Thanks for the suggestion. Quick question, do you think it makes sense to scale this by the monitor DPI? If you have a 4K monitor at 200% DPI, I feel it makes sense to apply 40px increase, however, want to hear opinions.

That's a good question. Not sure if there's a right or wrong answer.

I guess there's a couple ways to look at it.

1. If the user has different DPI monitors, the behavior may seem inconsistent when resizing.
2. There could be two different sets of key binds. One that uses an "auto resize factor" (i.e. based on DPI / current behavior) and the other that uses the value indicated, regardless of DPI. That gives the user the option instead of forcing a behavior on them.
3. So the user isn't trying to figure out what value to use because of DPI scaling, maybe it's simpler to just explicitly set the pixels and they can use the value that makes sense for their resolution / size monitors.
