### ISSUE TITLE
Automatic Window Sizing Detection

### ISSUE THREAD

**Issue by remiteeple** [FancyWM/fancywm#32]
**Is your feature request related to a problem? Please describe.**
Applications with minimum or maximum sizes are not detected natively and result in Z-Fighting occasionally.  i.e. Steam has a minimum width bound that prevents the window from being too small.  Additionally, if an application has minimum and maximum limits but is tiled, any tile padding is ignored.

**Describe the solution you'd like**
When an application is opened, it should be evaluated for minimum and maximum window widths, if the minimums conflict with existing tiled applications (overlap) the new application should be made floating as default.  If the applications .exe is known the result can be cached and said cache entry can be invalidated when a change is detected to the exe file has been modified.

**Describe alternatives you've considered**
In the case of Steam I usually make the application full screen to avoid tiling with it entirely.

**Additional context**
**Yellow Highlight:** Application minimum bounds attempting to be exceeded resulting in tile padding omission.
**Red Highlight:** Application minimum bound attempting to be exceeded resulting in window tile overlaps.
![image](https://user-images.githubusercontent.com/20644236/151218480-d69ef762-adf5-483f-b24b-39f8e1702dde.png)

**Comment by remiteeple** [comment]
I'm not sure if you're accessing WINAPI at some level but [this](https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-getminmaxinfo?redirectedfrom=MSDN) should solve this issue given appropriate handling...  [Here is some example usage for you.](https://stackoverflow.com/a/19035866) Hope it helps!

**Comment by veselink1** [comment]
WM_GETMINMAXINFO is being used https://github.com/FancyWM/winman-windows/blob/5d6457c63276f713c55493321470fc8379d0157d/src/WinMan.Windows/Windows/Win32Window.cs#L792

Steam seems to require special handling. Thanks :)

**Comment by veselink1** [comment]
By special handling, I mean there should probably be a list with sensible values for applications such as Steam which report their minimum size to be 0.
