### ISSUE TITLE
Run Automatically At Startup cannot be disabled.

### ISSUE THREAD

**Issue by adrynalyne** [FancyWM/fancywm#39]
**Describe the bug**
Run Automatically At Startup cannot be disabled.

**To Reproduce**
1. Start FancyWM.
2. Open Settings.
2. Disable Run Automatically At Startup.
3. Click Quit.
4. Re-open application.
5. Open Settings.
5. Run Automatically At Startup is re-enabled.

**Expected behavior**
To be able to stop FancyWM from automatically starting up when disabling the setting.

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Version 22000.469

**Additional context**
App version 2.4.1.0

**Comment by veselink1** [comment]
Thanks for reporting this. 

While this is being fixed, you should be able to disable FancyWM at startup by going into Task Manager > Startup.
