### ISSUE TITLE
Reduce Memory Usage

### ISSUE THREAD

**Issue by pc-v2** [FancyWM/fancywm#41]
**Describe the bug**
200MB for managing window seems kinda big?

**To Reproduce**
1. Run fancywm
2. check memory usage

**Expected behavior**
less bloated memory usage (<100MB)
**Screenshots**
![image](https://user-images.githubusercontent.com/58063311/152188191-8f3e164d-abc4-4da5-8a7d-20436c90182b.png)**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Version [e.g. 21H2 64-bit]

**Comment by veselink1** [comment]
Thanks for reporting this. 

I can only suggest closing the Settings window when not using it, as keeping it open is definitely going to result in increased CPU and memory usage, as in the screenshot. 

With the Settings window closed, the private heap peaks at 37 MiB (.NET objects), and Task Manager reports 160 MiB (on my machine, in debug). The 123 MiB difference between these two values is what is used by the platform (WPF, .NET, etc.) and as such is not directly under my control.

![Screenshot 2022-02-02 160200](https://user-images.githubusercontent.com/12015256/152191043-0107a8c0-0520-4f4e-a604-c316f31a28ac.png)

As far as I'm aware, there are no memory leaks, so for the time being, I see no practical way of reducing memory usage further without removing functionality. Sorry.
