### ISSUE TITLE
Stack panel inside stack panel

### ISSUE THREAD

**Issue by diocletiann** [FancyWM/fancywm#45]
Promising app, the closest one to i3 that I've seen for Windows. Hopefully you get to keep improving it!

**Is your feature request related to a problem? Please describe.**
No way to move a window to a "maximized upper level"

**Describe the solution you'd like**
I would like to create a top-level stack which would hold all windows I have promoted to "maximized", and then two nested stacks for windows that don't currently need the entire screen. This way you could "shift-win enter" on any window and send to the upper stack.

**Describe alternatives you've considered**
Traditional maximize removes the window from the layout and obscures GUI, requires Win combos or manually moving the window back into the original stack, and makes it harder to track what is maximized and what isn't.

**Comment by veselink1** [comment]
Hi there, thanks for opening a feature request.

I have to ask for clarification, as I cannot relate to the given use case. Where would the two nested stacks be on the screen when another window is maximised? Can you indicate the hierarchy of panels via bullets? This is what I interpret it as:
  - Stack ("maximised window stack")
    - Window 1
    - Window 2 
    - Vertical ("the two small stacks")
      - Stack 1
      - Stack 2

Unmaximising a window should return it to its original panel. Please indicate if that is the case for you.

**Comment by restfuladi** [comment]
Hi, thanks for the reply. Let me see if I can clarify:

It could work just like i3, when window from the topmost tack is selected that is not tiled or split the windows of the nested stacks would be obscured by the focused maximized window. You'd still see the tab bars and know they are open and how to get to them, but the space below the bars would be dedicated to the selected window which is not tiled or split. And you'd be able to promote windows up to maximized or down to a the split nested area.

Your hierarchy is correct, the top stack would hold either windows that don't get split/tiled or nested panels in which you could stack, just like i3. Rough example:

![image](https://user-images.githubusercontent.com/14058796/152925177-68c98f3b-3a06-460f-a64e-fb3552ce1a45.png)


I tried un-maximizing and yes it does return the window to its original panel, but then you're managing two different systems with different controls and if you minimize you have to re-add it the window to a panel. You also can't "demote" a window into a nested panel like you can in i3.
