### ISSUE TITLE
Move the focus to an adjacent window is limited to current monitor

### ISSUE THREAD

**Issue by Huray-hub** [FancyWM/fancywm#47]
**Is your feature request related to a problem? Please describe.**
Currently

**Describe the solution you'd like**

On the focused window, at the edge of the monitor, change focus 
to a window in monitor2 (if there is one), both horizontally and vertically.

**Comment by mwohlert** [comment]
+1

The feature should also include being able to move windows to different monitors by moving them right or left or directly to a specific monitor.
