### ISSUE TITLE
Save Window Management State and Loads it at Startup

### ISSUE THREAD

**Issue by pc-v2** [FancyWM/fancywm#51]
**Is your feature request related to a problem? Please describe.**
Current implementations is temporarily set.

**Describe the solution you'd like**
Saving the state, and load it after log out or add menus in system tray to set like in Pop!OS

**Additional context**
![image](https://user-images.githubusercontent.com/58063311/153033763-43727a85-ac33-47b5-be98-d635a7b8915b.png)

**Comment by abd1tus** [comment]
I'd really like to second this.  I have a set pattern I like windows in (which I assume do most people would would be interested in a tiling window manger).  Between windows restarts or windows occasionally acting like I plugged in a new monitor after my existing monitor sleeps, I loose the position on windows.  I'd really like:

-  the ability to save named layout profiles, pick between them
- have the profiles be aware of multiple monitors (I have 3) and always assign the same layout if the monitor is "rediscovered" by windows and move all the apps back to it that were there before
-  bonus if I can export them or share them with other computers via drop box or other shared drive utils. 
- The ability to set rules that certain apps always appear in the same spot (e.g. slack and discord) even after reopening
