### ISSUE TITLE
Launch on startup with Administrator privileges doesn't skip UAC

### ISSUE THREAD

**Issue by RixzZ** [FancyWM/fancywm#59]
**Describe the bug**
When you enable the launch on startup and the option to run as Administrator, on every boot you are greeted with an UAC window asking for permission to elevate privileges.

**To Reproduce**
1. Enable 'Run Automatically at System Startup' and 'Run with Administrator privileges'.
2. Restart the computer.
3. When the app starts an UAC window appears to ask for permission.

**Expected behavior**
As with other apps that have an option to run on startup as Administrator, the UAC window should be skipped. An example could be PowerToys, that has the same setting but doesn't trigger UAC on startup.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 21H2 64-bit (Build 22000.527)

**Additional context**
N/A

**Comment by pc-v2** [comment]
using task scheduler as bypass just like powertoys do 
![image](https://user-images.githubusercontent.com/58063311/155868679-0e0c91de-7181-4156-8e95-7f1521c0baca.png)

**Comment by RixzZ** [comment]
That doesn't seem possible with FancyWM, since trying to use the .exe in Task Scheduler, throws an error for Microsoft Store apps:
![image](https://user-images.githubusercontent.com/1339272/155885944-36d0e690-13b0-4710-bcda-b65ea423cd18.png)

**Comment by tejasraman** [comment]
Coming back to this in 2026 - you can indeed use task scheduler to open it. Just make sure to use conhost's headless option to avoid the cmd window popping up on login.

Here's how I set it up:

<img width="454" height="500" alt="Image" src="https://github.com/user-attachments/assets/70ee8a45-3d41-4522-82f0-5f45d063d58c" />

Arguments are `--headless "C:\Users\tejas\AppData\Local\Microsoft\WindowsApps\FancyWM.exe"`
