### ISSUE TITLE
Switch to Desktop x shortcut doesn't focus on the active window

### ISSUE THREAD

**Issue by Huray-hub** [FancyWM/fancywm#61]
**To Reproduce**
1. Map some keys to switch Desktops with shortcuts
2. Switch to desktop x using default window shortcuts (touchpad gesture 4fingers swipe left/right or Ctrl+Alt+Left/Right arrow key)
    You will observe that you are focused on the active window of that desktop
3. Switch to desktop x using shortcuts from FancyWM
4. You will observe that you are not focused on the active window of that desktop and need to left-click before, for example, starting writing

**Expected behavior**
Autofocus to the last active window of the desktop on desktop switch

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 21H2
 - OS Build: 22000.527 (latest)

**Comment by DinMon** [comment]
I don't know if this help, but I created a release with the fix https://github.com/DinMon/fancywm/releases/tag/v2.18.2.3-combined-focus-fixes
