### ISSUE TITLE
When I reposition desktops (placing desktop 3 in front of desktop 2) shortcuts do not update 

### ISSUE THREAD

**Issue by Huray-hub** [FancyWM/fancywm#68]
**Describe the bug**

**To Reproduce**
1. Open FancyWM options and map your shortcuts to Switch to Desktop[1-9] (for me is Alt+[1-9]).
2. Try shortcut to make sure that Alt+2 goes to Desktop 2
3. Go to desktop overview (Win + Tab)
4. Drag with cursor Desktop 2 behind Desktop 3 to reposition
5. Now after closing the desktop overview. Try again to move to the second Desktop with Alt+2 in the row 
   (which currently is the one with the label "Desktop 3")
6. Instead of "Desktop 3" you are moved again to "Desktop 2", which is 3rd)

**Expected behavior**
Shortcuts are mapped to Desktop's position instead of Desktop's instance

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 21H2 Build 22000.556

**Use case that explains the value**
I map my desktops by Priority.
Example: 
1st desktop: Secondary chat (ex. WhatsApp/Messenger) / Music
2nd desktop: Mail apps
3rd desktop: Main chats (ex. discord/ms teams)
4rth desktop: Main desktop
Desktop: Main (work IDE & browser with work profile)
Desktop: An other main (college IDE & browser with college profile)
When I work I use work-desktop in 4rth place and the afternoon I swap with college-desktop 
(sorry for the unnecessary details)

**Comment by veselink1** [comment]
Thanks for reporting! I did not even know desktops could be rearranged.
