### ISSUE TITLE
License status cannot be verified when the Microsoft Store is offline

### ISSUE THREAD

**Issue by veselink1** [FancyWM/fancywm#70]
**Describe the bug**
A user has reported that the license status check fails when the Microsoft Store is offline. 

**To Reproduce**
[?]

**Expected behavior**
FancyWM license status should not reset.

**Additional context**
FancyWM expects that the Microsoft Store remembers and correctly reports the acquisition of a license even when offline, but some users report that is not the case. It is not clear how to reproduce this and whether this happens (e.g.) after the Microsoft Store caches are cleared, or the user explicitly logs out of the Store and then goes offline, etc.

**Comment by mgutz** [comment]
I'm in the Philiippines where internet can be spotty. If I restart the computer with no internet connection I see the nag message. 

Here's an idea. Create an encrypted token with expiry, say 1 day, that gets refreshed when Store is online. That way the nag message get suppressed for at least a day.

BTW, good job on this app!

**Comment by kohennigs** [comment]
Good Morning! 

Using Fancy WM on my job machine and still learning. 

**Problem**: 
I have no store login / chance to get one or use my personal. 
In this case i am getting message window above on every system start. 

Not that bad, but a litte bit .. you now. 

By the way: May it be possible to get FancyWM as a downloadable package beside the store?
(If i missed this option : sorry for that.)

Nice tool! Good Job! Thank You!

**Comment by veselink1** [comment]
FancyWM is now open source. Happy holidays.

**Comment by veselink1** [comment]
Pre-built binaries will be provided soon.
