### ISSUE TITLE
Cheat Engine main window isn't managed

### ISSUE THREAD

**Issue by BlobyJacky** [FancyWM/fancywm#72]
**Describe the bug**
Cheat Engine main application window is not managed

**To Reproduce**
1. Download and install Cheat Engine from [Github](https://github.com/cheat-engine/cheat-engine) or the [official website](https://www.cheatengine.org/)
2. Install FancyWM
3. Start FancyWM (No matter admin right)
4. Realize that the main application window cannot be wrapped, moved, resized. (Can only be set as a floating window)

**Expected behavior**
Be able to wrap, move or resize the window 

**Screenshots**
![image](https://user-images.githubusercontent.com/102456820/160270440-af7c00fd-1b48-4040-9391-4f123d8a7e29.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2 Build 19044.1586

**Comment by remiteeple** [comment]
Please ensure the following setting has been toggled on.  Without it you will be unable to manage privileged execution processes.
![image](https://user-images.githubusercontent.com/20644236/165553705-b419a1ba-b52a-4c68-800d-a3e5c933a0e5.png)
