### ISSUE TITLE
Add more powerful control through window dragging

### ISSUE THREAD

**Issue by Zwatotem** [FancyWM/fancywm#76]
**Is your feature request related to a problem? Please describe.**
When I want to go from 3 windows side-by-side to 1 left, 2 right vertically I have to go through what feels like to many steps.
1. Embed the rightmost window in a vertical panel.
2. Move the window to the aforementioned panel.
I am very used to managing layouts through dragging and snapping windows from vanilla Windows management, and this feels slower than dragging one window to the corner and selecting another one for the adjacent corner. I expect this to be faster in most, or all cases of repositioning windows.

**Describe the solution you'd like**
I would like to make it a one step process, to achieve the effect as above, by defining a gesture that wouldn't break any of existing behavious.
My proposition is as follows: If a window is dragged to the screen border opposite to its current layout flow (e.i. horizontal (top or bottom) border if it's in horizontal panel, vertical (left or right) border if it's in vertical panel) it automatically opens new panel with perpendicular direction. Additionally the window that is the closest at the time of releasing it pulled to this panel as well.

For example: I have three windows side by side. It's a horizontal layout, so dragging windows to the right or left edge only changes their order. But if I drag right window to the top, I get indication by my cursor that it will create a vertical panel. When I release, it becomes the top-right window in that panel, and the middle window is moved to the bottom as the closest one. However if I released on the top towards the left, the left window would be pulled, and the whole panel would be placed on the left, leaving the middle window now on the right half.

**Describe alternatives you've considered**
More advanced mouse only or mouse + modifier key gestures, making a "shovel" out of your mouse. While holding a window being able to pick up more windows with right mouse button, pick type of panel with your scroll wheel or something, and where you drop off all the picked up windows are placed in a desired panel.
This requires more input for the example problem, but is still fast and more flexible (better generalized). 

**Additional context**
Of course both of these solutions are pretty advanced to implement, so I'm not pushing. I'm waiting for the creator to give his opinion on this. I have my fingers crossed for the development of this tiler, so I wanted to help with some design propositions. Keep up the great work 👍

**Comment by veselink1** [comment]
Thanks for sharing. These are some good ideas for improvement. In general, I try to steer clear of using the non-primary mouse buttons as hotkeys, because then only mouse users can use them. I'm experimenting with a more interactive approach which is kind of similar to what you've suggested, but more work is needed.

**Comment by veselink1** [comment]
Still a work in progress, but I think it's getting somewhere. Panels can be created by grouping two windows together, by "dragging" an action from the window actions. All feedback is appreciated. Thanks. 


https://user-images.githubusercontent.com/12015256/172923674-b7151fbe-fa8a-49e3-b89f-c5dfae147625.mp4
