### ISSUE TITLE
Workspase isn't refreshing after With-Increase/Decrase using direct shortcuts

### ISSUE THREAD

**Issue by aspidxt** [FancyWM/fancywm#77]
If you set [experimental DIRECT] shortcut for Increase/Decrase of Weight/Height and use it, windows will change it size only when they receive some extra event (change focus, for ex)

Similar
#23

**Comment by aspidxt** [comment]
Also it's will be cool to have configurable step size for increase/decrease width/heihgth  actions;)

**Comment by ishchow** [comment]
This also happens when using the scripting support (fancywm.exe calls). Reproduced using FancyWM v2.6.70.

OS Info:
```
OS Name	Microsoft Windows 10 Pro
Version	10.0.19044 Build 19044
```

**Comment by ishchow** [comment]
Here's a workaround as an AHK script until bug is fixed:

```ahk
; Invokes key press after activation shortcut
InvokeFancyWmAction(key)
{
	Send, {LWin down}{Shift down}
	Sleep, 100
	Send, {LWin up}{Shift up}
	Send, {%key%}
	Return
}

; Change the width/height of the focused window. Ctrl + Vim keys
; Decrease width
^h::InvokeFancyWmAction("[")

; Decrease height
^j::InvokeFancyWmAction(";")

; Increase height
^k::InvokeFancyWmAction("'")

; Increase width
^l::InvokeFancyWmAction("]")
```
