### ISSUE TITLE
Toggle Rules for currently selected window 

### ISSUE THREAD

**Issue by remiteeple** [FancyWM/fancywm#80]
**Is your feature request related to a problem? Please describe.**
When using FancyWM and encountering an application that you would like to create an exclusion rule for it can be cumbersome to open the settings panel and manually enter the process' name / window class.

**Describe the solution you'd like**
I suggest adding key-bindings to toggle an application or window class from the exclusion rules.  This would allow for quick exclusion using only keyboard commands.

**Describe alternatives you've considered**
Manually floating a window every time I encounter it or manually entering the process's information to permanently exclude it from being managed.

**Comment by veselink1** [comment]
Thanks for the feature request. A rule can also be quickly added from the windows actions, which is related to what you are after I believe? 

![image](https://user-images.githubusercontent.com/12015256/168253292-bde74e8d-7f78-4289-8acf-e3213375ae36.png)
