### ISSUE TITLE
Rules for automatically floating windows - enable by TitleText + process name?

### ISSUE THREAD

**Issue by llinfeng** [FancyWM/fancywm#83]
**Is your feature request related to a problem? Please describe.**
I use multiple monitors and sometimes span a window across multiple monitors. To organize these things, I use AutoHotKey [Groups](https://www.autohotkey.com/docs/commands/GroupAdd.htm) to define group-specific shortcut to perform the window-spanning action. For example, I use Jupyter notebook in Chrome over display 1 and 3, with the following display layout:
![image](https://user-images.githubusercontent.com/5890407/166332964-ba4bb37c-5bc7-45dc-b1fb-927476cb6642.png)

For now, after spanning the window across two monitors, by default, when I move the focus away from it, FancyWM shall resize the large spanning window to one monitor. Then, I'll need to redo the spanning action again. To stop this behavior, I added the following rule. However, I would like other "normal" Chrome windows to be managed by FancyWM.
![image](https://user-images.githubusercontent.com/5890407/166333553-518e1cbb-ea8c-4425-be00-ef0c264809b2.png)

**Describe the solution you'd like**
Please support syntax likes "Title + process name", so that I can ask FancyWM to automatically float only windows of a certain process with a matching TitleText. In the example above, I'd like to set auto-float only for "Jupyter chrome", where the first bit is part of the Window-Title, and the second piece denotes the process name.

**Describe alternatives you've considered**
An alternative is to treat TitleText by itself, in a Whitelist (or Blacklist) format - any windows with a matching text will then be excluded from the panel controlled by FancyWM.

**Additional context**
The whitelist approach may be cause less problem in the long run - parsing "Title+`process_name`" won't always work as both the title and the `process_name` can have spaces in them. (Yes, someone includes white space in their process name!)

**Comment by veselink1** [comment]
Thanks for the feature request.
