### ISSUE TITLE
Keep taskbar on top of managed windows

### ISSUE THREAD

**Issue by cryoteeth** [FancyWM/fancywm#85]
**Is your feature request related to a problem? Please describe.**
If the taskbar is set to ‘Automatically hide the taskbar in desktop mode’ the managed windows will always be on top of the taskbar, making it difficult-to-impossible to interact with the taskbar.

**Describe the solution you'd like**
Taskbar retains default behaviour of popping up over other windows.

**Comment by veselink1** [comment]
Thanks for reporting this. Unfortunately, I have not been able to reproduce this behaviour on the machines I have access to so a fix will take longer. 

- Does this happen when the "Automatically hide taskbar" option is enabled?
- What OS version and device are you experiencing this with?

Thanks.

**Comment by TomGillen** [comment]
I can reproduce this. When I enable "Automatically hide the taskbar in desktop mode", and then move the mouse to the edge of the screen to show the taskbar, it pops up underneath any windows.

Opening the taskbar with the windows key (to open the start menu) will cause it to pop up correctly on top of windows.

Running Windows 10, 10.0.19044 Build 19044.

**Comment by siba-dog-cap** [comment]
I have the same problem, the first time I start FancyWM it hides the taskbar, but the second time I start it the problem does not occur. In rare cases it works fine the first time, but I don't know why.
Surface go 3
Windows11 Pro 22H2 22623.1250

**Comment by KirilOkun** [comment]
Exactly same problem here.  Pretty annoying.  Windows 11Pro 22H2

**Comment by jon-love** [comment]
This is still an issue on Windows 11.
