### ISSUE TITLE
Smart padding/gaps for windows

### ISSUE THREAD

**Issue by Mistreaper** [FancyWM/fancywm#86]
**Is your feature request related to a problem? Please describe.**
Windows still have padding when it's only one window tiling, which is pretty annoying.
**Describe the solution you'd like**
This is a feature similar to "smart gaps" in i3-gaps. Basically, when there is only one window tiling, "smart gaps" remove the padding on windows, which reduces your distraction.

I really wish this project was open source though, there are a lot of people wanting to contribute.

**Comment by ngeraks** [comment]
Either that (no gaps) ooor have HUGE gaps for a single window. So it takes just the center of the screen (e.g. for TV users)
