### ISSUE TITLE
Provide a key binding to equally size windows in the current frame or window

### ISSUE THREAD

**Issue by rcronk** [FancyWM/fancywm#87]
**Is your feature request related to a problem? Please describe.**
When I restore a minimized window it often comes up small or large and I have to resize it multiple times with "[" or "]" or by dragging with the mouse.

**Describe the solution you'd like**
I'd like a key binding like "=" that resizes all windows in the current group (screen or vert/horiz frame) to be equally wide or tall.

**Comment by ariccb** [comment]
Ooh I'd like this as well
