### ISSUE TITLE
Move windows between screens

### ISSUE THREAD

**Issue by b-rodrigues** [FancyWM/fancywm#88]
With multiple screen, it would be great if "Move *direction*" would also work across screens. For instance, suppose that screen 1 is on the left of screen 2. 

Suppose I have a window opened in screen 1 that I’d like to move to screen 2. "Move Right" now show a popup (Could not move to Right! No adjacent Window) but it would be great if this was allowed to happen.

**Comment by NylonDiamond** [comment]
This is my biggest request as well. I always use 2 to 3 monitors and It's a pain to have to use the mouse all the time.
