### ISSUE TITLE
Allow panel locking

### ISSUE THREAD

**Issue by boarder2** [FancyWM/fancywm#91]
**Is your feature request related to a problem? Please describe.**
It can be frustrating to have new windows appear in whichever panels application has focus at the time the application is launched.

**Describe the solution you'd like**
Allow me to lock panels so new windows won't be automatically added to that panel unless I manually add them. Always require a minimum of 1 unlocked panel so new windows have somewhere to go.

**Comment by boarder2** [comment]
An alternative implementation could be the concept of a "primary" panel where all new windows will be added. Perhaps also adding an option for that panel to not go away even if the last window in it was closed.

**Comment by ariccb** [comment]
I very much like this idea. I think you could go as far as to maybe have an option to be able to specify exactly which panel will get every new window?
