### ISSUE TITLE
Focusing a split container in order to apply movement on it

### ISSUE THREAD

**Issue by sim590** [FancyWM/fancywm#97]
**Is your feature request related to a problem? Please describe.**

Suppose you have the following hierarchy of windows and split container:

```
   H      
  / \     
 /   \    
W1    V   
      /\  
     /  \ 
    W2  W3
```

where windows are denoted `Wn` with `n` a number and `H`,`V` respectively denote horizontally and vertically split containers.

You just can't move W1 on the right side of the vertically split container on the right in order to get this:
```
      H    
     / \   
    /   \  
   V     W1
  /\       
 /  \      
W2  W3     
```

**Describe the solution you'd like**

I would like the scenario described above to be possible. For this specific case, I see two solutions:

1. Allowing to move windows on the right even if no column (or branch) is already created on the right. Indeed, in i3, i'd simply focus the window W1 and move it to the right twice. The first time, the window W1 would be placed in the vertically split container (as it is the case in FancyWM), but the second time moving the window would create move the window on the right in a new branch and give the finally wanted state. Right now, FancyWM shows this instead:

<div align=center>
  <img align=center src="https://user-images.githubusercontent.com/4147254/172950884-282de37c-244b-49ca-9f70-0b8a84537c74.png" alt="" width="500px" />
</div>

2. Allowing to focus a split container in order to move them. It can be done right now with the mouse, but there is not way to do so with the keyboard it seems. On i3, I would use a key combination in order to elevate the focus to the parent node (speaking about the tree data structure representing the layout). Then, I could move the container like any other window.

**Describe alternatives you've considered**

For now, I can resolve the situation by moving the container from the right to the left **with the mouse** but that defeats the purpose of using FancyWM if you have to use your mouse. It's nice to have that option, but I want to keep my hands on the keyboard at all time if possible.

**Comment by veselink1** [comment]
Thanks for the feature request. This is being worked on.

**Comment by sim590** [comment]
@veselink1: I saw that you said it was being worked on, but the bot closed the ticket. Does that mean that you're abandoning the idea of working on this?
